service: fresco-slackbot
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${opt:stage}
  region: eu-west-3
  
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 
          path: '{proxy+}'
          method: any          

plugins:
  - serverless-offline